"""
Barcode Utility Functions
Helper functions for barcode operations, statistics, export, and import
"""

import csv
import json
from datetime import datetime, timedelta
import frappe
from frappe import _


def get_barcode_history(limit=100):
	"""
	Get history of generated barcodes
	:param limit: Number of records to return
	:return: List of barcode logs
	"""
	try:
		barcodes = frappe.get_all(
			'Barcode Log',
			fields=['name', 'barcode_string', 'vendor_code', 'part_code', 'qty', 'generated_on', 'generated_by'],
			order_by='generated_on desc',
			limit_page_length=limit
		)
		return {'status': 'success', 'data': barcodes}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def get_barcode_statistics():
	"""
	Get statistics about barcode generation
	:return: Statistics dictionary
	"""
	try:
		total_barcodes = frappe.db.count('Barcode Log')
		
		# Get stats by vendor
		vendor_stats = frappe.db.sql("""
			SELECT vendor_code, COUNT(*) as count
			FROM `tabBarcode Log`
			GROUP BY vendor_code
			ORDER BY count DESC
		""", as_dict=True)
		
		# Get stats by part
		part_stats = frappe.db.sql("""
			SELECT part_code, COUNT(*) as count
			FROM `tabBarcode Log`
			GROUP BY part_code
			ORDER BY count DESC
			LIMIT 10
		""", as_dict=True)
		
		# Get today's count
		today = datetime.now().date()
		today_count = frappe.db.count(
			'Barcode Log',
			{'generated_on': ('>=', str(today))}
		)
		
		stats = {
			'total_barcodes': total_barcodes,
			'today_generated': today_count,
			'vendor_statistics': vendor_stats,
			'part_statistics': part_stats
		}
		
		return {'status': 'success', 'data': stats}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def check_expiry_barcodes(days_ahead=30):
	"""
	Check for barcodes that are expiring soon
	:param days_ahead: How many days ahead to check
	:return: List of expiring barcodes
	"""
	try:
		target_date = datetime.now() + timedelta(days=days_ahead)
		
		expiring_barcodes = frappe.db.sql("""
			SELECT name, barcode_string, vendor_code, part_code, exp_date
			FROM `tabBarcode Log`
			WHERE exp_date <= %s AND exp_date >= %s
			ORDER BY exp_date ASC
		""", (target_date.date(), datetime.now().date()), as_dict=True)
		
		return {
			'status': 'success',
			'days_ahead': days_ahead,
			'data': expiring_barcodes
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def export_barcode_log(filters=None):
	"""
	Export barcode log to CSV
	:param filters: Dictionary of filters to apply
	:return: CSV content
	"""
	try:
		query = 'SELECT * FROM `tabBarcode Log` WHERE 1=1'
		params = []
		
		if filters:
			if filters.get('vendor_code'):
				query += ' AND vendor_code = %s'
				params.append(filters['vendor_code'])
			if filters.get('part_code'):
				query += ' AND part_code = %s'
				params.append(filters['part_code'])
			if filters.get('date_from'):
				query += ' AND DATE(generated_on) >= %s'
				params.append(filters['date_from'])
			if filters.get('date_to'):
				query += ' AND DATE(generated_on) <= %s'
				params.append(filters['date_to'])
		
		query += ' ORDER BY generated_on DESC'
		
		barcodes = frappe.db.sql(query, params, as_dict=True)
		
		if not barcodes:
			return {'status': 'error', 'message': 'No barcodes found with the given filters'}
		
		# Convert to CSV format
		csv_data = []
		csv_data.append(['Barcode String', 'Vendor Code', 'Part Code', 'Batch No', 
		                  'Packet Serial', 'Mfg Date', 'Exp Date', 'Qty', 'Constant Text', 
		                  'Generated By', 'Generated On'])
		
		for barcode in barcodes:
			csv_data.append([
				barcode.get('barcode_string'),
				barcode.get('vendor_code'),
				barcode.get('part_code'),
				barcode.get('batch_no'),
				barcode.get('packet_serial'),
				barcode.get('mfg_date'),
				barcode.get('exp_date'),
				barcode.get('qty'),
				barcode.get('constant_text'),
				barcode.get('generated_by'),
				barcode.get('generated_on')
			])
		
		return {
			'status': 'success',
			'data': csv_data,
			'count': len(barcodes)
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def import_barcode_log(file_data):
	"""
	Import barcode logs from CSV
	:param file_data: CSV file data
	:return: Import result
	"""
	try:
		imported_count = 0
		errors = []
		
		# Parse CSV
		csv_reader = csv.DictReader(file_data.splitlines())
		
		for row in csv_reader:
			try:
				log = frappe.new_doc('Barcode Log')
				log.barcode_string = row['Barcode String']
				log.vendor_code = row['Vendor Code']
				log.part_code = row['Part Code']
				log.batch_no = row['Batch No']
				log.packet_serial = row['Packet Serial']
				log.mfg_date = row['Mfg Date']
				log.exp_date = row['Exp Date']
				log.qty = row['Qty']
				log.constant_text = row['Constant Text']
				log.insert(ignore_if_exists=True)
				imported_count += 1
			except Exception as e:
				errors.append(f"Row error: {str(e)}")
		
		frappe.db.commit()
		
		return {
			'status': 'success',
			'imported': imported_count,
			'errors': errors
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def validate_item_availability(item_code, warehouse=None):
	"""
	Check item availability in warehouse
	:param item_code: Item code to check
	:param warehouse: Warehouse to check (optional)
	:return: Availability information
	"""
	try:
		if not warehouse:
			warehouse = frappe.db.get_single_value('Stock Settings', 'default_warehouse')
		
		stock = frappe.get_value(
			'Bin',
			{'item_code': item_code, 'warehouse': warehouse},
			['actual_qty', 'reserved_qty', 'projected_qty']
		)
		
		if stock:
			return {
				'status': 'success',
				'available': True,
				'actual_qty': stock[0],
				'reserved_qty': stock[1],
				'projected_qty': stock[2]
			}
		else:
			return {
				'status': 'success',
				'available': False,
				'message': f'Item {item_code} not found in {warehouse}'
			}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def bulk_generate_barcodes(data_list):
	"""
	Generate multiple barcodes at once
	:param data_list: List of barcode data dictionaries
	:return: Generated barcodes list
	"""
	try:
		from barcode_api import generate_barcode
		
		results = []
		for data in data_list:
			result = generate_barcode(json.dumps(data))
			results.append(result)
		
		return {
			'status': 'success',
			'generated': len([r for r in results if r['status'] == 'success']),
			'failed': len([r for r in results if r['status'] == 'error']),
			'results': results
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def archive_old_barcodes(days=90):
	"""
	Archive barcode logs older than specified days
	:param days: Number of days threshold
	:return: Archive result
	"""
	try:
		cutoff_date = datetime.now() - timedelta(days=days)
		
		old_barcodes = frappe.db.count(
			'Barcode Log',
			{'generated_on': ('<', cutoff_date)}
		)
		
		# Mark as archived (you might need to add an archived field to the DocType)
		frappe.db.sql("""
			UPDATE `tabBarcode Log`
			SET docstatus = 2
			WHERE generated_on < %s
		""", cutoff_date)
		
		frappe.db.commit()
		
		return {
			'status': 'success',
			'archived_count': old_barcodes,
			'cutoff_date': str(cutoff_date)
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


# import re
# import json
# from datetime import datetime

# import frappe
# from frappe import _
# import barcode as python_barcode
# from barcode.writer import ImageWriter
# import qrcode
# from io import BytesIO
# import base64


# def validate_barcode_data(data):
# 	"""Validate barcode data format and field lengths."""
# 	errors = []

# 	vendor = (data.get("vendor_code") or "").strip()
# 	if not vendor or len(vendor) > 8:
# 		errors.append(_("Vendor Code is required (max 8 characters)"))

# 	part = (data.get("part_code") or "").strip()
# 	if not part or len(part) > 10:
# 		errors.append(_("Part Code is required (max 10 characters)"))

# 	batch = (data.get("batch_no") or "").strip()
# 	if not batch or len(batch) > 14:
# 		errors.append(_("Batch Number is required (max 14 characters)"))

# 	packet = (data.get("packet_serial") or "").strip()
# 	if not packet or len(packet) > 7:
# 		errors.append(_("Packet Serial is required (max 7 characters)"))

# 	mfg_date = (data.get("mfg_date") or "").strip()
# 	if not mfg_date or not re.match(r"^\d{6}$", mfg_date):
# 		errors.append(_("Manufacturing Date must be 6 digits in YYMMDD format"))
# 	else:
# 		try:
# 			datetime.strptime(mfg_date, "%y%m%d")
# 		except ValueError:
# 			errors.append(_("Manufacturing Date is not a valid date"))

# 	exp_date = (data.get("exp_date") or "").strip()
# 	if not exp_date or not re.match(r"^\d{6}$", exp_date):
# 		errors.append(_("Expiry Date must be 6 digits in YYMMDD format"))
# 	else:
# 		try:
# 			datetime.strptime(exp_date, "%y%m%d")
# 		except ValueError:
# 			errors.append(_("Expiry Date is not a valid date"))

# 	qty = (data.get("qty") or "").strip()
# 	if not qty or not qty.isdigit() or len(qty) > 7:
# 		errors.append(_("Quantity must be up to 7 digits"))

# 	constant = (data.get("constant_text") or "").strip()
# 	if not constant or len(constant) != 1 or not constant.isalpha():
# 		errors.append(_("Constant Text must be exactly 1 alphabetic character"))

# 	if errors:
# 		frappe.throw("<br>".join(errors), title=_("Validation Error"))

# 	return True


# def build_barcode_string(data):
# 	"""Build barcode string: vendor/part/batch/packet/mfg/exp/qty/constant"""
# 	return "/".join([
# 		data.get("vendor_code", "").strip(),
# 		data.get("part_code", "").strip(),
# 		data.get("batch_no", "").strip(),
# 		data.get("packet_serial", "").strip(),
# 		data.get("mfg_date", "").strip(),
# 		data.get("exp_date", "").strip(),
# 		data.get("qty", "").strip(),
# 		data.get("constant_text", "").strip(),
# 	])


# def get_code_type():
# 	"""Get configured code type from Vecmocon Settings (Barcode or QR Code)."""
# 	return frappe.db.get_single_value("Vecmocon Settings", "code_type") or "Barcode"


# def generate_code_image(text):
# 	"""Generate Code128 barcode or QR Code PNG as base64 data URI based on settings."""
# 	code_type = get_code_type()
# 	buf = BytesIO()

# 	if code_type == "QR Code":
# 		qr = qrcode.QRCode(version=1, box_size=6, border=2)
# 		qr.add_data(text)
# 		qr.make(fit=True)
# 		img = qr.make_image(fill_color="black", back_color="white")
# 		img.save(buf, format="PNG")
# 	else:
# 		code128 = python_barcode.get("code128", text, writer=ImageWriter())
# 		code128.write(buf, options={"write_text": True, "module_height": 15.0, "module_width": 0.3, "quiet_zone": 2.0})

# 	buf.seek(0)
# 	return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


# @frappe.whitelist()
# def generate_barcode(data):
# 	"""Generate barcode string + Code128 barcode image without saving a log."""
# 	if isinstance(data, str):
# 		data = json.loads(data)

# 	validate_barcode_data(data)
# 	barcode_string = build_barcode_string(data)

# 	existing = frappe.db.get_value("Barcode Log", {"barcode_string": barcode_string}, "name")
# 	if existing:
# 		return {
# 			"barcode_string": barcode_string,
# 			"barcode_image": generate_code_image(barcode_string),
# 			"barcode_log": existing,
# 			"already_exists": True,
# 		}

# 	return {
# 		"barcode_string": barcode_string,
# 		"barcode_image": generate_code_image(barcode_string),
# 	}


# @frappe.whitelist()
# def save_barcode_log(data):
# 	"""Generate barcode image and save a Barcode Log entry."""
# 	if isinstance(data, str):
# 		data = json.loads(data)

# 	validate_barcode_data(data)
# 	barcode_string = build_barcode_string(data)

# 	existing = frappe.db.get_value("Barcode Log", {"barcode_string": barcode_string}, "name")
# 	if existing:
# 		return {
# 			"barcode_log": existing,
# 			"barcode_string": barcode_string,
# 			"barcode_image": generate_code_image(barcode_string),
# 			"already_exists": True,
# 		}

# 	qr_image = generate_code_image(barcode_string)

# 	log = frappe.new_doc("Barcode Log")
# 	log.barcode_string = barcode_string
# 	log.vendor_code = data["vendor_code"].strip()
# 	log.part_code = data["part_code"].strip()
# 	log.batch_no = data["batch_no"].strip()
# 	log.packet_serial = data["packet_serial"].strip()
# 	log.mfg_date = datetime.strptime(data["mfg_date"].strip(), "%y%m%d").strftime("%Y-%m-%d")
# 	log.exp_date = datetime.strptime(data["exp_date"].strip(), "%y%m%d").strftime("%Y-%m-%d")
# 	log.qty = data["qty"].strip()
# 	log.constant_text = data["constant_text"].strip()
# 	log.generated_by = frappe.session.user
# 	log.generated_on = frappe.utils.now()
# 	log.save(ignore_permissions=True)
# 	frappe.db.commit()

# 	return {
# 		"barcode_log": log.name,
# 		"barcode_string": barcode_string,
# 		"barcode_image": qr_image,
# 	}


# def parse_barcode_string(barcode_string):
# 	"""Split a barcode string into its 8 components."""
# 	parts = barcode_string.strip().split("/")
# 	if len(parts) != 8:
# 		frappe.throw(
# 			_("Invalid barcode format. Expected 8 fields separated by '/', got {0}").format(len(parts))
# 		)
# 	return {
# 		"vendor_code": parts[0],
# 		"part_code": parts[1],
# 		"batch_no": parts[2],
# 		"packet_serial": parts[3],
# 		"mfg_date": parts[4],
# 		"exp_date": parts[5],
# 		"qty": parts[6],
# 		"constant_text": parts[7],
# 	}


# @frappe.whitelist()
# def scan_barcode(barcode_string):
# 	"""
# 	Parse a scanned barcode and return ERPNext-mapped field values.
# 	Looks up Item by part_code and Supplier by vendor_code.
# 	"""
# 	parsed = parse_barcode_string(barcode_string)

# 	mfg_date = datetime.strptime(parsed["mfg_date"], "%y%m%d").strftime("%Y-%m-%d")
# 	exp_date = datetime.strptime(parsed["exp_date"], "%y%m%d").strftime("%Y-%m-%d")
# 	qty = int(parsed["qty"])

# 	# --- Item lookup ---
# 	item_code = parsed["part_code"]
# 	item_name = ""
# 	uom = ""
# 	has_batch_no = 0
# 	has_serial_no = 0
# 	if frappe.db.exists("Item", item_code):
# 		item_doc = frappe.get_cached_doc("Item", item_code)
# 		item_name = item_doc.item_name
# 		uom = item_doc.stock_uom
# 		has_batch_no = item_doc.has_batch_no
# 		has_serial_no = item_doc.has_serial_no

# 	# --- Auto-create Batch if item has batch tracking and batch doesn't exist ---
# 	batch_no = parsed["batch_no"]
# 	if has_batch_no and batch_no and not frappe.db.exists("Batch", batch_no):
# 		batch_doc = frappe.new_doc("Batch")
# 		batch_doc.batch_id = batch_no
# 		batch_doc.item = item_code
# 		batch_doc.manufacturing_date = mfg_date
# 		batch_doc.expiry_date = exp_date
# 		batch_doc.save(ignore_permissions=True)
# 		frappe.db.commit()

# 	# --- Supplier lookup via supplier_part_no in Item Supplier ---
# 	supplier = ""
# 	supplier_name = ""
# 	vendor_code = parsed["vendor_code"]
# 	sup_link = frappe.db.get_value(
# 		"Item Supplier", {"supplier_part_no": vendor_code}, "supplier"
# 	)
# 	if sup_link:
# 		supplier = sup_link
# 		supplier_name = frappe.get_value("Supplier", sup_link, "supplier_name") or ""

# 	return {
# 		"item_code": item_code,
# 		"item_name": item_name,
# 		"uom": uom,
# 		"batch_no": parsed["batch_no"],
# 		"serial_no": parsed["packet_serial"],
# 		"qty": qty,
# 		"mfg_date": mfg_date,
# 		"exp_date": exp_date,
# 		"supplier": supplier,
# 		"supplier_name": supplier_name,
# 		"vendor_code": vendor_code,
# 		"constant_text": parsed["constant_text"],
# 		"has_batch_no": has_batch_no,
# 		"has_serial_no": has_serial_no,
# 	}


# @frappe.whitelist()
# def get_barcode_image(barcode_string):
# 	"""Regenerate barcode/QR code image from a barcode string based on settings."""
# 	if not barcode_string:
# 		frappe.throw(_("Barcode string is required"))
# 	return generate_code_image(barcode_string)


# @frappe.whitelist()
# def get_code_type_setting():
# 	"""Return current code type setting for frontend use."""
# 	return get_code_type()


# @frappe.whitelist()
# def custom_scan_barcode(search_value):
# 	"""
# 	Override ERPNext's erpnext.stock.utils.scan_barcode.
# 	If the scanned value matches our custom format (8 fields separated by /),
# 	parse it using our logic. Otherwise, fall through to ERPNext's default.
# 	"""
# 	search_value = (search_value or "").strip()

# 	# Check if it matches our custom format
# 	if "/" in search_value and len(search_value.split("/")) == 8:
# 		return scan_barcode(search_value)

# 	# Fall through to ERPNext's original scan_barcode
# 	from erpnext.stock.utils import scan_barcode as erp_scan_barcode
# 	return erp_scan_barcode(search_value)


# @frappe.whitelist()
# def get_items_for_vendor(vendor_code):
# 	"""Get items whose Item Supplier child has the given supplier_part_no (Vendor Part Code)."""
# 	vendor_code = (vendor_code or "").strip()
# 	if not vendor_code:
# 		return []

# 	rows = frappe.get_all(
# 		"Item Supplier",
# 		filters={"supplier_part_no": vendor_code},
# 		fields=["parent as item_code", "supplier"],
# 	)

# 	result = []
# 	for row in rows:
# 		item_name = frappe.get_value("Item", row["item_code"], "item_name") or ""
# 		supplier_name = frappe.get_value("Supplier", row["supplier"], "supplier_name") or ""
# 		result.append({
# 			"item_code": row["item_code"],
# 			"item_name": item_name,
# 			"supplier": row["supplier"],
# 			"supplier_name": supplier_name,
# 		})
# 	return result


# @frappe.whitelist()
# def item_query_for_vendor(doctype, txt, searchfield, start, page_len, filters):
# 	"""Link field query: return Items whose Item Supplier child has the given supplier_part_no."""
# 	vendor_code = (filters.get("vendor_code") or "").strip()

# 	if not vendor_code:
# 		return frappe.db.sql("""
# 			SELECT name, item_name FROM `tabItem`
# 			WHERE (name LIKE %(txt)s OR item_name LIKE %(txt)s)
# 			ORDER BY name
# 			LIMIT %(start)s, %(page_len)s
# 		""", {"txt": f"%{txt}%", "start": start, "page_len": page_len})

# 	return frappe.db.sql("""
# 		SELECT DISTINCT i.name, i.item_name
# 		FROM `tabItem` i
# 		INNER JOIN `tabItem Supplier` its ON its.parent = i.name
# 		WHERE its.supplier_part_no = %(vendor_code)s
# 		AND (i.name LIKE %(txt)s OR i.item_name LIKE %(txt)s)
# 		ORDER BY i.name
# 		LIMIT %(start)s, %(page_len)s
# 	""", {"vendor_code": vendor_code, "txt": f"%{txt}%", "start": start, "page_len": page_len})

# import frappe
# import base64
# from io import BytesIO
# import barcode
# from barcode.writer import ImageWriter


# def create_barcode(text):
# 	CODE128 = barcode.get_barcode_class('code128')
# 	writer = ImageWriter()
# 	buffer = BytesIO()
# 	CODE128(text, writer=writer).write(buffer)
# 	return "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()


# def format_date(date):
# 	if not date:
# 		return ""
# 	return date.strftime("%y%m%d")


# def build_string(d):
# 	return f"{d['vendor_code']}/{d['part_code']}/{d['batch_no']}/{d['mfg_date']}/{d['exp_date']}/{d['qty']}/{d['constant_text']}"


# @frappe.whitelist()
# def generate_barcode_bulk(data):
# 	data = frappe.parse_json(data)
# 	result = []

# 	for d in data:
# 		barcode_string = build_string(d)
# 		img = create_barcode(barcode_string)

# 		result.append({
# 			"barcode_string": barcode_string,
# 			"barcode_image": img,
# 			"part_code": d.get("part_code"),
# 			"batch_no": d.get("batch_no"),
# 			"qty": d.get("qty")
# 		})

# 	return result


# @frappe.whitelist()
# def save_barcode_bulk(data, purchase_receipt):
# 	data = frappe.parse_json(data)
# 	result = []

# 	for d in data:
# 		barcode_string = build_string(d)
# 		img = create_barcode(barcode_string)

# 		doc = frappe.get_doc({
# 			"doctype": "Barcode Log",
# 			"vendor_code": d.get("vendor_code"),
# 			"part_code": d.get("part_code"),
# 			"mpn": d.get("mpn"),
# 			"batch_no": d.get("batch_no"),
# 			"qty": d.get("qty"),
# 			"barcode_string": barcode_string,
# 			"purchase_receipt": purchase_receipt
# 		})
# 		doc.insert(ignore_permissions=True)

# 		result.append({
# 			"barcode_string": barcode_string,
# 			"barcode_image": img,
# 			"part_code": d.get("part_code"),
# 			"batch_no": d.get("batch_no"),
# 			"qty": d.get("qty")
# 		})

# 	return result