"""
Barcode Utility Functions
Helper functions for barcode operations, statistics, export, and import
"""

import csv
import json
from datetime import datetime, timedelta
import frappe
from frappe import _


def get_barcode_history(limit=100):
	"""
	Get history of generated barcodes
	:param limit: Number of records to return
	:return: List of barcode logs
	"""
	try:
		barcodes = frappe.get_all(
			'Barcode Log',
			fields=['name', 'barcode_string', 'vendor_code', 'part_code', 'qty', 'generated_on', 'generated_by'],
			order_by='generated_on desc',
			limit_page_length=limit
		)
		return {'status': 'success', 'data': barcodes}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def get_barcode_statistics():
	"""
	Get statistics about barcode generation
	:return: Statistics dictionary
	"""
	try:
		total_barcodes = frappe.db.count('Barcode Log')
		
		# Get stats by vendor
		vendor_stats = frappe.db.sql("""
			SELECT vendor_code, COUNT(*) as count
			FROM `tabBarcode Log`
			GROUP BY vendor_code
			ORDER BY count DESC
		""", as_dict=True)
		
		# Get stats by part
		part_stats = frappe.db.sql("""
			SELECT part_code, COUNT(*) as count
			FROM `tabBarcode Log`
			GROUP BY part_code
			ORDER BY count DESC
			LIMIT 10
		""", as_dict=True)
		
		# Get today's count
		today = datetime.now().date()
		today_count = frappe.db.count(
			'Barcode Log',
			{'generated_on': ('>=', str(today))}
		)
		
		stats = {
			'total_barcodes': total_barcodes,
			'today_generated': today_count,
			'vendor_statistics': vendor_stats,
			'part_statistics': part_stats
		}
		
		return {'status': 'success', 'data': stats}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def check_expiry_barcodes(days_ahead=30):
	"""
	Check for barcodes that are expiring soon
	:param days_ahead: How many days ahead to check
	:return: List of expiring barcodes
	"""
	try:
		target_date = datetime.now() + timedelta(days=days_ahead)
		
		expiring_barcodes = frappe.db.sql("""
			SELECT name, barcode_string, vendor_code, part_code, exp_date
			FROM `tabBarcode Log`
			WHERE exp_date <= %s AND exp_date >= %s
			ORDER BY exp_date ASC
		""", (target_date.date(), datetime.now().date()), as_dict=True)
		
		return {
			'status': 'success',
			'days_ahead': days_ahead,
			'data': expiring_barcodes
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def export_barcode_log(filters=None):
	"""
	Export barcode log to CSV
	:param filters: Dictionary of filters to apply
	:return: CSV content
	"""
	try:
		query = 'SELECT * FROM `tabBarcode Log` WHERE 1=1'
		params = []
		
		if filters:
			if filters.get('vendor_code'):
				query += ' AND vendor_code = %s'
				params.append(filters['vendor_code'])
			if filters.get('part_code'):
				query += ' AND part_code = %s'
				params.append(filters['part_code'])
			if filters.get('date_from'):
				query += ' AND DATE(generated_on) >= %s'
				params.append(filters['date_from'])
			if filters.get('date_to'):
				query += ' AND DATE(generated_on) <= %s'
				params.append(filters['date_to'])
		
		query += ' ORDER BY generated_on DESC'
		
		barcodes = frappe.db.sql(query, params, as_dict=True)
		
		if not barcodes:
			return {'status': 'error', 'message': 'No barcodes found with the given filters'}
		
		# Convert to CSV format
		csv_data = []
		csv_data.append(['Barcode String', 'Vendor Code', 'Part Code', 'Batch No', 
		                  'Packet Serial', 'Mfg Date', 'Exp Date', 'Qty', 'Constant Text', 
		                  'Generated By', 'Generated On'])
		
		for barcode in barcodes:
			csv_data.append([
				barcode.get('barcode_string'),
				barcode.get('vendor_code'),
				barcode.get('part_code'),
				barcode.get('batch_no'),
				barcode.get('packet_serial'),
				barcode.get('mfg_date'),
				barcode.get('exp_date'),
				barcode.get('qty'),
				barcode.get('constant_text'),
				barcode.get('generated_by'),
				barcode.get('generated_on')
			])
		
		return {
			'status': 'success',
			'data': csv_data,
			'count': len(barcodes)
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def import_barcode_log(file_data):
	"""
	Import barcode logs from CSV
	:param file_data: CSV file data
	:return: Import result
	"""
	try:
		imported_count = 0
		errors = []
		
		# Parse CSV
		csv_reader = csv.DictReader(file_data.splitlines())
		
		for row in csv_reader:
			try:
				log = frappe.new_doc('Barcode Log')
				log.barcode_string = row['Barcode String']
				log.vendor_code = row['Vendor Code']
				log.part_code = row['Part Code']
				log.batch_no = row['Batch No']
				log.packet_serial = row['Packet Serial']
				log.mfg_date = row['Mfg Date']
				log.exp_date = row['Exp Date']
				log.qty = row['Qty']
				log.constant_text = row['Constant Text']
				log.insert(ignore_if_exists=True)
				imported_count += 1
			except Exception as e:
				errors.append(f"Row error: {str(e)}")
		
		frappe.db.commit()
		
		return {
			'status': 'success',
			'imported': imported_count,
			'errors': errors
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def validate_item_availability(item_code, warehouse=None):
	"""
	Check item availability in warehouse
	:param item_code: Item code to check
	:param warehouse: Warehouse to check (optional)
	:return: Availability information
	"""
	try:
		if not warehouse:
			warehouse = frappe.db.get_single_value('Stock Settings', 'default_warehouse')
		
		stock = frappe.get_value(
			'Bin',
			{'item_code': item_code, 'warehouse': warehouse},
			['actual_qty', 'reserved_qty', 'projected_qty']
		)
		
		if stock:
			return {
				'status': 'success',
				'available': True,
				'actual_qty': stock[0],
				'reserved_qty': stock[1],
				'projected_qty': stock[2]
			}
		else:
			return {
				'status': 'success',
				'available': False,
				'message': f'Item {item_code} not found in {warehouse}'
			}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def bulk_generate_barcodes(data_list):
	"""
	Generate multiple barcodes at once
	:param data_list: List of barcode data dictionaries
	:return: Generated barcodes list
	"""
	try:
		from barcode_api import generate_barcode
		
		results = []
		for data in data_list:
			result = generate_barcode(json.dumps(data))
			results.append(result)
		
		return {
			'status': 'success',
			'generated': len([r for r in results if r['status'] == 'success']),
			'failed': len([r for r in results if r['status'] == 'error']),
			'results': results
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}


def archive_old_barcodes(days=90):
	"""
	Archive barcode logs older than specified days
	:param days: Number of days threshold
	:return: Archive result
	"""
	try:
		cutoff_date = datetime.now() - timedelta(days=days)
		
		old_barcodes = frappe.db.count(
			'Barcode Log',
			{'generated_on': ('<', cutoff_date)}
		)
		
		# Mark as archived (you might need to add an archived field to the DocType)
		frappe.db.sql("""
			UPDATE `tabBarcode Log`
			SET docstatus = 2
			WHERE generated_on < %s
		""", cutoff_date)
		
		frappe.db.commit()
		
		return {
			'status': 'success',
			'archived_count': old_barcodes,
			'cutoff_date': str(cutoff_date)
		}
	except Exception as e:
		return {'status': 'error', 'message': str(e)}
